spring.application.name=dz3_MTS
server.port=8080

management.endpoints.web.base-path=/admin
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=false
management.endpoint.health.show-details=always

spring.security.user.name=admin
spring.security.user.password=password
spring.security.user.roles=ADMIN

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.example.dz3_MTS=DEBUG

spring.aop.auto=true